apiVersion: v1
kind: PersistentVolume
metadata:
  name: ruslan-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mr/zk